# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcar',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.AlterModelTable(
            name='shopcar',
            table='shop_car',
        ),
    ]
