"""
Django settings for tmall project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 加密密钥 用户系统 session
SECRET_KEY = '+e4s69w%n*+7@fzfhxw=_eejgke=7)e&o(t*pu4$ehkf&kz%_y'

# SECURITY WARNING: don't run with debug turned on in production!
# 开发的时候用的，上线的时候要改为False
DEBUG = True
# DEBUG = False
# 允许所有的ip都能访问我们的服务器
ALLOWED_HOSTS = ['*']

# Application definition

# 系统内置的app
SYS_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
# 自定义的app
CUSTOM_APPS = [
    'apps.search',
    'apps.account',
    'apps.cars',
    'apps.home',
    'apps.order',
]
# 第三方扩展的
EXT_APPS = [
    # 验证码扩展包
    # 'captcha',
    # xadmin核心app
    'xadmin',
    'crispy_forms',
    # 主题相关
    'reversion',

]
# 注册APP
INSTALLED_APPS = SYS_APPS + CUSTOM_APPS + EXT_APPS

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tmall.urls'

# 模板
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tmall.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tmall',
        'USER': 'root',
        'PASSWORD': '1995',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# 添加静态文件的存放路径，使用相对路径
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# 访问的多媒体文件的路径前缀
MEDIA_URL = '/media/'
# 配置上传文件的根目录
# MEDIA_ROOT = BASE_DIR + 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 配置缓存
CACHES = {
    # redis缓存
    'default': {
        # 指定使用哪种缓存配置方式
        'BACKEND': 'django_redis.cache.RedisCache',
        # redis缓存地址的配置
        'LOCATION': 'redis://139.199.164.245:6379/0',
        # 缓存失效时间
        'TIMEOUT': 300,
        "OPTIONS": {
            # "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "PASSWORD": "1995",
        }
    },
    # # 文件缓存
    # 'default': {
    #     # 使用文件缓存
    #     'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
    #     # 配置缓存的目录
    #     'LOCATION': 'file://D:/django_cache/cache',
    #     'TIMEOUT': '100',
    # }
    'session_cache': {
        # 指定使用哪种缓存配置方式
        'BACKEND': 'django_redis.cache.RedisCache',
        # redis缓存地址的配置
        'LOCATION': 'redis://139.199.164.245:6379/2',
        # 缓存失效时间
        'TIMEOUT': 300,
        "OPTIONS": {
            # "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "PASSWORD": "1995",
        }
    }
}

# 设置redis存储session
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'session_cache'

# session 全局配置
# SESSION_COOKIE_NAME='sessionid'
SESSION_COOKIE_PATH = '/'  # 限制的路径
SESSION_COOKIE_AGE = 60 * 60  # 过期的时间
SESSION_EXPIRE_AT_BROWSER_COLSE = True  # 浏览器关闭时，session是否失效

# 如果30分钟没有和服务器通信，session就会失效
SESSION_SAVE_EVERY_REQUEST = True
# 用户认证相关的
# AUTH_USER_MODEL = ''
# 邮件的相关的配置

# 支付宝相关配置
# 支付宝应用的ID
APP_ID = '2016091800540558'
# 支付宝网关
ALI_PAY_URL = 'https://openapi.alipaydev.com/gateway.do'
# 设置自己私匙
APP_PRIVATE_STRING = 'MIIEowIBAAKCAQEAux61PufKtOtgr0DTQlBXi0qnAic16bYfu3mTY9ZpOIvM4IFhxKzaj+NjDKwdYngDzKzkrsvgNxRtUtkXYuMUlOyvwYOv9GqYNiNi0Q/Cs9I+Jx3MfQmyIb5X++MDzhN454/Eb5KCWsDFHnvc6CoPPyo+MLCxzZrzpVF8nmIoKQeHRFEXKC9rmQ6mn6xnFtX5uHO/JQn7U2rtfUH29qRekHKIw4H7Q80j/m7KjGQqnbqlo4QWjT3C6YGZKd93utqZywOwWOm4K4Yv9vhXU1PNOcrtX1/Q1Ew2JOJi6TUm9h8xEbhvKnk7LYwHhEcwaqKNCAbHJ/ZbiK+TeO75OXbMXQIDAQABAoIBAEs+0/+R0k/ifyS6WrnF+Q5IXNRe1C1BUY1gHEb/h5x3i1GUda5THCjUdZY4+DAKtuxtciBgV6+OhU/VgLQBQNuKOjsFK5KL8t2CaVBMmC0blGbCcuKtLXaoRlVCOtt5tRrZE1MShVzdO+dAQ9sQXsU1xYBq7XUSpHuMQyKlsiSc9EzFflsXgcHI9uqwvKwBEAb49/+hTnMW/7RpG0PzcPa3KWwfWEpYscaCBjd2AvwaHrXINnX7Ik8GjcuqZL+F+0DAO8swfJVORMS/+fjzCxsqgA+hiSeImIMIg/sYeFJQy50TZij6L8xQ6WQWQIfNqjz7wixkAcBrHRTOTdGi3kECgYEA4USs2eHHO1k37X9BRpwzag1JEti3dts/VzPCXMz6zyW2AlXhi5tL817sT4jKpysG3FuOcgjxFoTheMT4gnC66VnJrFQcYuYMoCNC66TjrnRXnWLxoiWYaoTf0UF7R1fyO3dkAztsLAu32eFpWKWFZrap0xe9GzxTBoj+4OHKrlUCgYEA1KW7U/r9WMhZ0Kgz4WPKXlJaQv5igXlDebvmnIrGZs+zkUuZ54fbPI87LGoKSZdLI+ml6Jv8ZRxnbaMMwrhFs637eOvfnen2MLzLy1+q92iW5GnBJpwI3ogpgwei/kRthMR6bgdBMh3gyiz2eKamMWKnY7GqtUTVphjW3yrEnekCgYEAwRXKSt95k+c/RvSikNFmSGqmzd6wMtJukmItILoZ6OBcB9hxAObVzP758po/idYZhVt810XO0AyJ7qh2kefqbgWmFW3q/uJMxB41SCIHfgr+5kpe7yrmX7cQ2R4VeutpF4uYUCTo7UAGEF1jnLYTiBzdp7BbSTMFvz5BqaQfxBkCgYArUeP6tMv91Tru1gVTqkektXQr57TbmX+UgiH1zBOlCDUVqWgeEcAo8yjj4GpeGZM2Krggzf45/vJXFHtaA743X382YB77BZmgziVaNhAXPNhYie7OVcU8yFJknh6nW/tPq9MhLRssAYg0x7oiVBjRQL7HAX+8U9yObMsBRa4uWQKBgEpjlXu0ZajhU2SPne3dDbpQviXpcr+SU/U2UlrPRQEpUHr2L1NKEP0NnzmvDxkm9nJxfYDp8Qf0zYLXtbVYFTIHasshJq8FumkW9nC5cedHsJMABfb29rgRYje0unS9kC5Yj02uVoOOvDS4fKzItJc+p8wuHw2nZe1+Tve0Hedn'
# 将自己的公匙放在支付宝上
ALI_PAY_PUBLIC_KEY_STRING = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAux61PufKtOtgr0DTQlBXi0qnAic16bYfu3mTY9ZpOIvM4IFhxKzaj+NjDKwdYngDzKzkrsvgNxRtUtkXYuMUlOyvwYOv9GqYNiNi0Q/Cs9I+Jx3MfQmyIb5X++MDzhN454/Eb5KCWsDFHnvc6CoPPyo+MLCxzZrzpVF8nmIoKQeHRFEXKC9rmQ6mn6xnFtX5uHO/JQn7U2rtfUH29qRekHKIw4H7Q80j/m7KjGQqnbqlo4QWjT3C6YGZKd93utqZywOwWOm4K4Yv9vhXU1PNOcrtX1/Q1Ew2JOJi6TUm9h8xEbhvKnk7LYwHhEcwaqKNCAbHJ/ZbiK+TeO75OXbMXQIDAQAB'


if __name__ == '__main__':
    print('\n'.join([''.join([('Love'[(x - y) % len('Love')] if ((x * 0.05) ** 2 + (y * 0.1) ** 2 - 1) ** 3 - (
            x * 0.05) ** 2 * (y * 0.1) ** 3 <= 0 else ' ') for x in range(-30, 30)]) for y in range(30, -30, -1)]))
